"use client";
import {useEffect,useRef,useState} from "react";
import {products} from "@/lib/products";
type Upload={file:File;url:string};

export default function PhotoStudio(){
 const input=useRef<HTMLInputElement>(null),[photo,setPhoto]=useState<Upload|null>(null),[productId,setProductId]=useState(products[0].id),[result,setResult]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{if(result)URL.revokeObjectURL(result)},[result]);
 useEffect(()=>()=>{if(photo)URL.revokeObjectURL(photo.url)},[photo]);
 function clearResult(){if(result)URL.revokeObjectURL(result);setResult("")}
 function upload(file?:File){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setStatus("Please use JPG, PNG or WebP.");return}if(file.size>8*1024*1024){setStatus("Keep the photo under 8 MB.");return}clearResult();setPhoto({file,url:URL.createObjectURL(file)});setStatus("Photo ready on this device. Choose a garment and generate your preview.");if(input.current)input.current.value=""}
 function remove(){clearResult();setPhoto(null);setStatus("Photo removed from this device.")}
 async function generate(){if(!photo)return;setBusy(true);clearResult();setStatus("CatVTON is preparing your private preview. The first run can take several minutes…");try{const body=new FormData();body.append("photo",photo.file);body.append("productId",productId);const response=await fetch("/api/try-on",{method:"POST",body});if(!response.ok){const text=await response.text();let message=`Try-on unavailable (${response.status}).`;try{message=JSON.parse(text).error||message}catch{}throw new Error(message)}setResult(URL.createObjectURL(await response.blob()));setStatus("Preview generated locally. Visual appearance only—not a sizing guarantee.")}catch(error){setStatus(error instanceof Error?error.message:"Generation failed.")}finally{setBusy(false)}}
 return <section className="photo-studio"><div><span>PRIVATE FITTING PROFILE / 01</span><h2>Your photo,<br/><i>under your control.</i></h2><p>Choose one clear, full-body photo. It stays in your browser until you request a preview, then is processed once by the configured AI provider and is not retained by this site.</p><ul><li>Stand straight, facing the camera</li><li>Use bright, even lighting</li><li>JPG, PNG or WebP · maximum 8 MB</li></ul></div><div className={`dropzone ${photo?"has-photo":""}`}>{photo?<><img src={photo.url} alt="Your uploaded full-body preview"/><div className="try-controls"><select value={productId} onChange={event=>setProductId(event.target.value)} aria-label="Garment to try on">{products.map(product=><option key={product.id} value={product.id}>{product.brand} — {product.name}</option>)}</select><button onClick={()=>void generate()} disabled={busy}>{busy?"Generating…":"Try it on"}</button></div><div className="photo-actions"><button onClick={()=>input.current?.click()} disabled={busy}>Replace photo</button><button onClick={remove} disabled={busy}>Delete</button></div>{result&&<div className="try-result"><figure><img src={photo.url} alt="Before try-on"/><figcaption>BEFORE</figcaption></figure><figure><img src={result} alt="AI-generated virtual try-on"/><figcaption>AI PREVIEW</figcaption></figure><button onClick={clearResult}>Close</button></div>}</>:<button onClick={()=>input.current?.click()} disabled={busy}><b>＋</b><strong>Add a full-body photo</strong><small>Choose from this device</small></button>}<input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>upload(event.target.files?.[0])}/>{status&&<p className="try-note" role="status">{status}</p>}</div></section>
}
